version: "3.8"
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: triuser
      POSTGRES_PASSWORD: tripass
      POSTGRES_DB: triathlon
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    ports: ["9000:9000"]
    volumes: [miniodata:/data]
volumes: { pgdata: {}, miniodata: {} }
